dataset:
  test:
    class: CoDesignDataset
    mmap_dir: /home/ubuntu/quang/peptide_design/benchmark dataset/datasets/pepbdb/processed_filtered_30
    specify_index: /home/ubuntu/quang/peptide_design/benchmark dataset/datasets/pepbdb/processed_filtered_30/test_index.txt
    backbone_only: false
    use_covariance_matrix: true

dataloader:
  num_workers: 4
  batch_size: 64

backbone_only: false
n_samples: 40

sample_opt:
  energy_func: default
  energy_lambda: 0.8
