dataset:
  test:
    class: CoDesignDataset
    mmap_dir: /home/ubuntu/quang/peptide_design/benchmark dataset/datasets/pepbdb/processed_filtered_30
    backbone_only: true
    use_covariance_matrix: true

dataloader:
  num_workers: 4
  batch_size: 64

backbone_only: true
n_samples: 40

sample_opt:
  energy_func: default
  energy_lambda: 0.8
